"""Public MCP registry scanner — populer sunuculari tarar."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

KNOWN_MPC_SERVERS: list[tuple[str, str, str]] = [
    # Official Anthropic / modelcontextprotocol
    (
        "@modelcontextprotocol/server-filesystem",
        "npx",
        "-y @modelcontextprotocol/server-filesystem /tmp",
    ),
    ("@modelcontextprotocol/server-github", "npx", "-y @modelcontextprotocol/server-github"),
    (
        "@modelcontextprotocol/server-postgres",
        "npx",
        "-y @modelcontextprotocol/server-postgres localhost:5432",
    ),
    (
        "@modelcontextprotocol/server-brave-search",
        "npx",
        "-y @modelcontextprotocol/server-brave-search",
    ),
    (
        "@modelcontextprotocol/server-puppeteer",
        "npx",
        "-y @modelcontextprotocol/server-puppeteer",
    ),
    ("@modelcontextprotocol/server-slack", "npx", "-y @modelcontextprotocol/server-slack"),
    # Popular community servers
    (
        "@anthropic/server-sequential-thinking",
        "npx",
        "-y @anthropic/server-sequential-thinking",
    ),
    ("@tavily/server-tavily-search", "npx", "-y @tavily/server-tavily-search"),
    ("@smithery/server-git", "npx", "-y @smithery/server-git"),
    ("@smithery/server-fetch", "npx", "-y @smithery/server-fetch"),
]

README_RE = re.compile(
    r"-\s+\[([^\]]+)\]\(([^)]+)\)\s*[-–]\s*(.+)",
    re.MULTILINE,
)


@dataclass
class RegistryEntry:
    name: str
    install_command: str
    tools_count: int = 0
    findings_count: int = 0
    high_count: int = 0
    critical_count: int = 0
    status: str = "not_scanned"


def scan_registry(output_path: str | None = None, timeout: int = 30) -> list[dict[str, Any]]:
    """Scan known MCP servers and return results.

    Returns a list of dicts suitable for markdown table rendering.
    """
    results: list[dict[str, Any]] = []

    for name, _runner, full_cmd in KNOWN_MPC_SERVERS:
        entry = {
            "name": name,
            "command": full_cmd,
            "status": "not_scanned",
            "tools": 0,
            "findings": 0,
            "high": 0,
            "critical": 0,
        }
        results.append(entry)

    return results


def render_leaderboard(results: list[dict[str, Any]]) -> str:
    """Render scan results as a markdown leaderboard."""
    lines: list[str] = []
    lines.append("# MCP Server Security Leaderboard\n")
    lines.append(
        f"> Generated by [MCPRadar](https://github.com/yatuk/mcpradar) "
        f"— {len(results)} servers tracked\n"
    )
    lines.append("")
    lines.append(
        "| Server | Status | Tools | Findings | High | Critical |"
    )
    lines.append("|--------|--------|-------|----------|------|----------|")

    for r in results:
        status_icon = {
            "not_scanned": "⏳",
            "clean": "✅",
            "issues": "⚠️",
            "error": "❌",
        }.get(r["status"], "❓")

        lines.append(
            f"| {r['name']} | {status_icon} {r['status']} | "
            f"{r['tools']} | {r['findings']} | "
            f"{r['high']} | {r['critical']} |"
        )

    lines.append("")
    lines.append("## Legend\n")
    lines.append("| Icon | Status |")
    lines.append("|------|--------|")
    lines.append("| ⏳ | Not yet scanned |")
    lines.append("| ✅ | No issues found |")
    lines.append("| ⚠️ | Issues found |")
    lines.append("| ❌ | Scan failed |")
    lines.append("")

    return "\n".join(lines)
